# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FaceDetection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'NVActivityIndicatorView'
	pod 'Bond'
	pod 'ReactiveKit'


  # Pods for FaceDetection

end
